// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    BredsInfo: typeof import('./../src/views/home/components/breds/BredsInfo.vue')['default']
    Breeds: typeof import('./../src/views/home/components/breds/Breeds.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    Disliked: typeof import('./../src/views/home/components/Disliked.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Favorite: typeof import('./../src/views/home/components/Favorite.vue')['default']
    GalleryPage: typeof import('./../src/views/home/components/gallery/GalleryPage.vue')['default']
    GirlPage: typeof import('./../src/views/home/components/GirlPage.vue')['default']
    Home: typeof import('./../src/views/home/components/Home.vue')['default']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    LeftPage: typeof import('./../src/views/home/components/LeftPage.vue')['default']
    Liked: typeof import('./../src/views/home/components/Liked.vue')['default']
    PhotoUpload: typeof import('./../src/views/home/components/gallery/PhotoUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../src/views/home/components/SearchBar.vue')['default']
    SearchPage: typeof import('./../src/views/home/components/SearchPage.vue')['default']
    UploadPage: typeof import('./../src/views/home/components/gallery/UploadPage.vue')['default']
    Voting: typeof import('./../src/views/home/components/votong/Voting.vue')['default']
  }
}
